apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: harbor.riq-homelab.local:5000/auth-service:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret