apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: harbor.riq-homelab.local:5000/review-service:${IMAGE_TAG}
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret